title: WSU Quantum Sciences
logo: assets\logo\WSUQS_Logo.svg
description: A club that studies various quantum sciences at Wright State University
show_downloads: false

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one